on: [push]
jobs:
  test:
    timeout-minutes: 5
    runs-on: node-lts
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Build frontend
      run: npm run build-client
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run playwright tests
      run: npm run test
    - name: Run backend tests
      run: npm run test-backend


